# Generated by Django 3.0.5 on 2020-04-19 05:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Covid',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=25, null=True, verbose_name='Name')),
                ('group', models.CharField(blank=True, max_length=25, null=True, verbose_name='Group by country or city')),
                ('confirmed', models.BigIntegerField(verbose_name='Confirmed')),
                ('confirmed_changed', models.CharField(blank=True, max_length=225, null=True, verbose_name='Confirmed Change Today')),
                ('recovered', models.BigIntegerField(verbose_name='Recovered')),
                ('recovered_changed', models.FloatField(blank=True, null=True, verbose_name='Recovered Change Today')),
                ('deaths', models.BigIntegerField(verbose_name='Deaths')),
                ('deaths_changed', models.FloatField(blank=True, null=True, verbose_name='Deaths Change Today')),
                ('tests', models.BigIntegerField(verbose_name='Tests')),
                ('tests_changed', models.FloatField(blank=True, null=True, verbose_name='Tests Change Today')),
                ('ref_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='Refernce url')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, max_length=50, null=True)),
                ('scraped_key', models.CharField(blank=True, max_length=50, null=True)),
                ('table_name', models.CharField(blank=True, max_length=65, null=True)),
            ],
            options={
                'ordering': ['confirmed', 'deaths', 'recovered', 'tests'],
            },
        ),
    ]
