# Generated by Django 3.0.5 on 2020-04-22 02:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Covid',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=25, null=True, verbose_name='Name')),
                ('group', models.CharField(blank=True, max_length=25, null=True, verbose_name='Group by country or city')),
                ('total_case', models.IntegerField(blank=True, default=0, null=True, verbose_name='Total cases')),
                ('new_case', models.IntegerField(blank=True, default=0, null=True, verbose_name='New Cases')),
                ('total_recovered', models.IntegerField(blank=True, default=0, null=True, verbose_name='Total Recovered')),
                ('active_case', models.IntegerField(blank=True, default=0, null=True, verbose_name='Active Cases')),
                ('deaths', models.IntegerField(blank=True, default=0, null=True, verbose_name='Deaths')),
                ('new_deaths', models.IntegerField(blank=True, null=True, verbose_name='New Deaths')),
                ('tests', models.IntegerField(blank=True, default=0, null=True, verbose_name='Tests')),
                ('date', models.DateField(auto_now=True)),
                ('ref_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='Refernce url')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('last_scraped', models.DateTimeField(auto_now=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, max_length=50, null=True)),
                ('scraped_key', models.CharField(blank=True, max_length=50, null=True)),
                ('table_name', models.CharField(blank=True, max_length=65, null=True)),
            ],
            options={
                'ordering': ['total_case', 'new_case', 'deaths', 'tests'],
            },
        ),
    ]
