# Generated by Django 3.0.4 on 2020-03-08 04:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PAData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('zipcode', models.CharField(blank=True, max_length=25, null=True, verbose_name='Zipcode')),
                ('state', models.CharField(blank=True, max_length=25, null=True, verbose_name='State')),
                ('utility_name', models.CharField(blank=True, max_length=125, null=True, verbose_name='Utility Name')),
                ('utility_code', models.CharField(blank=True, max_length=125, null=True, verbose_name='Utility Code')),
                ('company_name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Company Name')),
                ('plan_type', models.CharField(blank=True, max_length=500, null=True, verbose_name='Plan type')),
                ('price_rate', models.FloatField(default=0, verbose_name='Price rate')),
                ('monthly_fee', models.FloatField(default=0, verbose_name='Monthly free')),
                ('enrollment_fee', models.FloatField(default=0, verbose_name='Enrollment fee')),
                ('cancellation_fee', models.FloatField(default=0, verbose_name='Cancellation fee')),
                ('term_length', models.CharField(blank=True, max_length=25, null=True, verbose_name='Term length')),
                ('renewable', models.CharField(blank=True, max_length=25, null=True, verbose_name='Renewable')),
                ('product_info', models.CharField(blank=True, max_length=500, null=True, verbose_name='Product info')),
                ('phone_number', models.CharField(blank=True, max_length=250, null=True, verbose_name='Phone number')),
                ('signup_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='Signup url')),
                ('product_last_update', models.DateField(blank=True, null=True, verbose_name='Product last update')),
                ('site_name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Site name')),
                ('domain_name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Domain name')),
                ('last_scraped', models.DateTimeField(auto_now_add=True, verbose_name='Scraped time')),
                ('ref_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='Refernce url')),
                ('table_name', models.CharField(blank=True, max_length=65, null=True)),
            ],
        ),
    ]
