# Generated by Django 3.0.5 on 2020-04-19 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='covid',
            name='tests_changed',
        ),
        migrations.AddField(
            model_name='covid',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
