# Generated by Django 3.0.5 on 2020-04-22 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='covid',
            options={'ordering': ['total_case', 'new_case', 'deaths', 'tests']},
        ),
        migrations.RemoveField(
            model_name='covid',
            name='confirmed',
        ),
        migrations.RemoveField(
            model_name='covid',
            name='confirmed_changed',
        ),
        migrations.RemoveField(
            model_name='covid',
            name='deaths_changed',
        ),
        migrations.RemoveField(
            model_name='covid',
            name='recovered',
        ),
        migrations.RemoveField(
            model_name='covid',
            name='recovered_changed',
        ),
        migrations.AddField(
            model_name='covid',
            name='new_case',
            field=models.BigIntegerField(blank=True, default=0, null=True, verbose_name='New Cases'),
        ),
        migrations.AddField(
            model_name='covid',
            name='new_deaths',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='New Deaths'),
        ),
        migrations.AddField(
            model_name='covid',
            name='total_case',
            field=models.BigIntegerField(blank=True, default=0, null=True, verbose_name='Total cases'),
        ),
        migrations.AddField(
            model_name='covid',
            name='total_recovered',
            field=models.BigIntegerField(blank=True, default=0, null=True, verbose_name='Total Recovered'),
        ),
    ]
