# Generated by Django 3.0.5 on 2020-04-22 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200422_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covid',
            name='active_case',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Active Cases'),
        ),
        migrations.AlterField(
            model_name='covid',
            name='deaths',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Deaths'),
        ),
        migrations.AlterField(
            model_name='covid',
            name='new_case',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='New Cases'),
        ),
        migrations.AlterField(
            model_name='covid',
            name='new_deaths',
            field=models.IntegerField(blank=True, null=True, verbose_name='New Deaths'),
        ),
        migrations.AlterField(
            model_name='covid',
            name='tests',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Tests'),
        ),
        migrations.AlterField(
            model_name='covid',
            name='total_case',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Total cases'),
        ),
        migrations.AlterField(
            model_name='covid',
            name='total_recovered',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Total Recovered'),
        ),
    ]
