# Generated by Django 3.0.4 on 2020-03-11 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200309_0707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='padata',
            name='product_info',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Product info'),
        ),
    ]
