# Generated by Django 3.0.5 on 2020-04-22 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200422_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covid',
            name='active_case',
            field=models.IntegerField(default=0, null=True, verbose_name='Active Cases'),
        ),
    ]
