# Generated by Django 3.0.5 on 2020-04-19 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_covid_last_scraped'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covid',
            name='confirmed',
            field=models.BigIntegerField(blank=True, default=0, null=True, verbose_name='Confirmed'),
        ),
        migrations.AlterField(
            model_name='covid',
            name='confirmed_changed',
            field=models.FloatField(blank=True, null=True, verbose_name='Confirmed Change Today'),
        ),
        migrations.AlterField(
            model_name='covid',
            name='deaths',
            field=models.BigIntegerField(blank=True, default=0, null=True, verbose_name='Deaths'),
        ),
        migrations.AlterField(
            model_name='covid',
            name='recovered',
            field=models.BigIntegerField(blank=True, default=0, null=True, verbose_name='Recovered'),
        ),
        migrations.AlterField(
            model_name='covid',
            name='tests',
            field=models.BigIntegerField(blank=True, default=0, null=True, verbose_name='Tests'),
        ),
    ]
