# Generated by Django 3.0.4 on 2020-03-12 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200311_0833'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='padata',
            options={'ordering': ['price_rate', 'zipcode', 'state', 'plan_type', 'term_length', 'monthly_fee']},
        ),
        migrations.AlterField(
            model_name='padata',
            name='term_length',
            field=models.IntegerField(blank=True, null=True, verbose_name='Term length'),
        ),
    ]
