# Generated by Django 3.0.5 on 2020-04-21 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200419_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='covid',
            name='active_case',
            field=models.BigIntegerField(blank=True, default=0, null=True, verbose_name='Active Cases'),
        ),
    ]
