# Generated by Django 3.0.4 on 2020-04-02 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200323_0255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='padata',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
