# Generated by Django 3.0.4 on 2020-04-03 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20200402_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='padata',
            name='new_customer_offer',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Fureture PTC date'),
        ),
        migrations.AddField(
            model_name='padata',
            name='term_of_service',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Fureture PTC date'),
        ),
    ]
