# Generated by Django 3.0.4 on 2020-04-03 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20200403_0353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='padata',
            name='new_customer_offer',
            field=models.CharField(blank=True, default='', max_length=225, null=True, verbose_name='New Customer Offer '),
        ),
        migrations.AlterField(
            model_name='padata',
            name='term_of_service',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Terms of Service '),
        ),
    ]
