# Generated by Django 3.0.5 on 2020-06-10 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20200610_0323'),
    ]

    operations = [
        migrations.AddField(
            model_name='padata',
            name='fact_sheet',
            field=models.FloatField(default=0, verbose_name='EFL Fact Sheet '),
        ),
    ]
