# Generated by Django 3.0.5 on 2020-06-10 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_padata_fact_sheet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='padata',
            name='fact_sheet',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='EFL Fact Sheet '),
        ),
    ]
