# Generated by Django 3.0.5 on 2020-06-12 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20200610_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='padata',
            name='cancellation_fee',
            field=models.FloatField(default=None, null=True, verbose_name='Cancellation fee'),
        ),
        migrations.AlterField(
            model_name='padata',
            name='enrollment_fee',
            field=models.FloatField(default=None, null=True, verbose_name='Enrollment fee'),
        ),
        migrations.AlterField(
            model_name='padata',
            name='fact_sheet',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='EFL Fact Sheet'),
        ),
        migrations.AlterField(
            model_name='padata',
            name='fiveh_kwh',
            field=models.FloatField(default=None, null=True, verbose_name='500 kWh'),
        ),
        migrations.AlterField(
            model_name='padata',
            name='monthly_fee',
            field=models.FloatField(default=None, null=True, verbose_name='Monthly free'),
        ),
        migrations.AlterField(
            model_name='padata',
            name='onek_kwh',
            field=models.FloatField(default=None, null=True, verbose_name='1000 kWh'),
        ),
        migrations.AlterField(
            model_name='padata',
            name='price_rate',
            field=models.FloatField(default=None, null=True, verbose_name='Price rate'),
        ),
        migrations.AlterField(
            model_name='padata',
            name='rating',
            field=models.FloatField(default=None, null=True, verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='padata',
            name='twok_kwh',
            field=models.FloatField(default=None, null=True, verbose_name='2000 kWh'),
        ),
    ]
